version: '3'
services:
  app:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env.development
    command: >
      bash -c "wait-for db:3306 -- flask run --host=0.0.0.0 --port=5000"
    depends_on:
      - db
    volumes:
      - .:/app

  tests:
    build: .
    env_file:
      - .env.development
    command: >
      bash -c "wait-for db:3306 -- pytest"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mariadb:latest
    env_file:
      - .env.development
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: